config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :bikes, only: [ :index, :destroy, :update, :create] do
    resources :rentals, only: [ :new, :create ]
  end
  resources :rentals, only: [ :index ]
  get '/search', to: 'bikes#search', as: :search
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bike.rb
class Bike < ApplicationRecord
  belongs_to :user
  has_one_attached :photo

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :name, presence: true, allow_blank: false
  validates :description, presence: true, allow_blank: false
  validates :price_per_hour, presence: true

  validate :has_photo?

  def has_photo?
    unless photo.attached?
      errors.add(:photo, "should be present")
    end
  end
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :user
  belongs_to :bike

  validates :end_date, presence: true
  validates :start_date, presence: true
  validate :start_date_is_valid, :end_date_is_valid

  private

  def start_date_is_valid
    if start_date.present? && start_date < DateTime.now
      errors.add(:start_date, "can't be in the past")
    end
  end

  def end_date_is_valid
    if end_date.present? && start_date.present?
      if end_date < DateTime.now
        errors.add(:end_date, "can't be in the past")
      elsif end_date <= start_date
        errors.add(:end_date, "can't be before start date")
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bikes, dependent: :destroy
  has_many :rentals, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end
  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/ || params[:controller] == "bikes" && params[:action] == "search"
  end
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  before_action :set_bike, only: %i[update destroy]
  skip_before_action :authenticate_user!, only: :search

  def index
    @bikes = policy_scope(Bike).order(created_at: :desc)
    @bike = Bike.new
  end

  def search
    @bikes = Bike.where(available: true)

    @markers = @bikes.map do |bike|
      {
        lat: bike.latitude,
        lng: bike.longitude
      }
    end
  end

  def destroy
    @bike.destroy
    redirect_to bikes_path
  end

  def update
    old_status = @bike.available
    @bike.update_column(:available, !old_status)
    authorize @bike

    respond_to do |format|
      format.html { redirect_to bikes_path }
      format.js { render 'bikes/update_availability.js.erb'}
    end
  end

  def create
    @bikes = policy_scope(Bike).order(created_at: :desc)
    @bike = Bike.new(bike_params)
    @bike.user = current_user

    authorize @bike
    if @bike.save
      redirect_to bikes_path
    else
      render :index
    end
  end

  private

  def bike_params
    params.require(:bike).permit(:name, :description, :price_per_hour, :available, :photo)
  end

  def set_bike
    @bike = Bike.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @bike = Bike.new
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :set_bike, only: [:create, :new]

  def index
    @rentals = policy_scope(Rental).order(created_at: :desc)
  end

  def new
    @rental = Rental.new
    authorize @rental
  end

  def create
    @rental = Rental.new(rental_params)
    @rental.user = current_user
    @rental.bike = @bike
    authorize @rental
    if @rental.save
      redirect_to rentals_path
    else
      render :new
    end
  end

  private

  def rental_params
    params.require(:rental).permit(:start_date, :end_date)
  end

  def set_bike
    @bike = Bike.find(params[:bike_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bikes/_map.html.erb
<div
id="map"
style="width: 100%;
height: 100vh;"
data-markers="<%= @markers.to_json %>"
data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
></div>

app/views/bikes/_my_bike_card.html.erb
<div class="border border-info m-2 w-80 bg-secondary">
  <div class="row">
    <div class="col">
      <%= cl_image_tag bike.photo.key, height: 120, width: 120, crop: :fill %>
    </div>
    <div class="col d-flex flex-column justify-content-between flex-grow">
      <h5 class="pt-2"><%= bike.name %></h5>
      <p><%= bike.description %></p>
    </div>
    <div class="col d-flex flex-column justify-content-between py-2">
      <h6><%= bike.price_per_hour %>€/h</h6>
      <div class="custom-control custom-switch">
        <%= link_to bike_path(bike), method: :patch, remote: true do %>
          <input
          data-bike-id="<%= bike.id %>"
          checked="<%= bike.available %>"
          type="checkbox"
          class="custom-control-input">
          <label class="custom-control-label" for="customSwitch1">Available</label>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bikes/_search_card.html.erb
<div class="border border-info m-2 w-80 bg-secondary">
  <div class="row">
    <div class="col">
      <%= cl_image_tag bike.photo.key, height: 120, width: 120, crop: :fill %>
    </div>
    <div class="col">
      <h6 class="m-2 text-left"><%= bike.name %></h6>
      <p class="m-2 small-text"><%= bike.description %></p>
    </div>
    <div class="col">
      <h6 class="m-2 text-right"><%= bike.price_per_hour %>€/h</h6>
    </div>
  </div>
</div>

app/views/bikes/_search_result_list.html.erb
<div class="container bottom-spacer">
  <div class="row justify-content-center pt-small">
    <div class="col">
      <% @bikes.each do |bike| %>
        <%= link_to new_bike_rental_path(bike) do %>
          <%= render 'search_card', bike: bike %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/bikes/index.html.erb
<%= render 'shared/top_navbar', title: 'All my bikes!' %>
<div class="container pt-small bottom-spacer ">
  <a data-toggle="collapse" href="#collapseAddform" role="button">
    <div class="w-80 dash-border border-info rounded d-flex p-3 justify-content-center align-items-center my-1">
      <i class="fas fa-plus-square fa-2x text-info" id="add-bike-button"></i>
    </div>
  </a>
  <div class="collapse w-75 mx-auto" id="collapseAddform">
    <%= simple_form_for @bike  do |f| %>
      <%= f.input :name, placeholder: 'Road Bike, Mountain Bike, Commuting Bike...' %>
      <%= f.input :description, placeholder: '7 gears, 2kg, ideal for city rides....'%>
      <%= f.input :price_per_hour %>
      <%= f.input :photo, as: :file %>
      <%= f.button :submit, class: 'btn btn-primary btn-block mb-2' %>
    <% end %>
  </div>
  <% @bikes.each do |bike| %>
    <%= render 'my_bike_card', bike: bike %>
  <% end %>
</div>

app/views/bikes/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-6">
      <%= simple_form_for @bike  do |f| %>
        <%= f.input :name %>
        <%= f.input :description %>
        <%= f.input :price_per_hour %>
        <%= f.input :photo, as: :file %>
        <%= f.button :submit, class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/bikes/search.html.erb
<%= render 'shared/top_navbar', title: 'Choose your ride!' %>
<button id="toggle-button" class="btn btn-primary btn-block" type="button" data-toggle="collapse" data-target=".collapse" aria-expanded="false" aria-controls="multiCollapseExample2">
  <i class="fas fa-list-ul"></i>
  Liste des vélos
</button>
<div class="collapse">
  <%= render 'search_result_list' %>
</div>
<div class="collapse show">
  <%= render 'map' %>
</div>

app/views/bikes/update_availability.js.erb
function updateToggle(status) {
  const availableBtn = document.querySelector("[data-bike-id='<%= @bike.id %>']");
  availableBtn.checked = status;
}

updateToggle(<%=  @bike.available %>);

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/navbar' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<%= render 'shared/top_navbar', title: 'Biclou' %>
<div class='jumbotron bg-info'>
  <div class="pt-4 vh-100">
    <div class="container w-75">
      <h2>Rent bikes by the hour or day!</h2>
      <p class="lead mb-4">All you need is a bike</p>
      <form action="/search" method="get">
        <div class="form-group my-auto">
          <input type="text" name="where" class="form-control my-2 bottom-line-input" id="home-search">
          <input class="btn btn-primary my-2" type="submit" value="search">
        </div>
      </form>
      <div class='pt-5 d-flex justify-content-center'>
      <%= cl_image_tag("output-onlinepngtools_1_nf4byr") %>
      </div>
    </div>
  </div>
</div>

app/views/rentals/_rental_card.html.erb
<div class="border border-info m-2 w-80 bg-secondary">
  <div class="row justiy-content-between">
    <div class="col">
      <%= cl_image_tag rental.bike.photo.key, height: 120, width: 120, crop: :fill %>
    </div>
    <div class="col d-flex flex-column justify-content-between">
      <h5 class="pt-2"><%= rental.bike.name.titleize %></h5>
      <div>
       <p class="small-text">
         <%= rental.start_date.strftime("%e %b %Y") %>
         <%= rental.start_date.strftime("%H:%M") %>
       </p>
     </div>
    </div>
    <div class="col d-flex flex-column justify-content-between">
     <h6 class="pt-2">Active now</h6>
     <div>
       <p class="small-text">
         <%= rental.end_date.strftime("%e %b %Y") %>
         <%= rental.end_date.strftime("%H:%M") %>
       </p>
     </div>
    </div>
  </div>
</div>

app/views/rentals/create.html.erb
<%= simple_form_for [@bike, @rental] do |f| %>
  <%= f.input :start_date %>
  <%= f.input :end_date %>
  <%= f.submit "Book a Bike", class: "btn btn-primary" %>
<% end %>

app/views/rentals/index.html.erb
<%= render 'shared/top_navbar', title: 'All my rentals!' %>
<div class="container bottom-spacer">
  <!-- How to add ynamically user name? -->
  <div class="row justify-content-center pt-2">
    <div class="col">
      <% @rentals.each do |rental| %>
        <%= render 'rental_card', rental: rental %>
      <% end %>
    </div>
  </div>
</div>

app/views/rentals/new.html.erb
<div class="container" id='newbike'>
  <%= simple_form_for [@bike, @rental] do |f| %>
    <%= f.input :start_date, as: :string, required: true, input_html: {class: "datePicker"} %>
    <%= f.input :end_date, as: :string, required: true, input_html: {class: "datePicker"} %>
    <%= f.submit "Book a Bike", class: "btn btn-primary btn-block" %>
  <% end %>
</div>

app/views/shared/_card.html.erb
<div class="mycard">
  <img class="card-image" src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
  <div class="card-content">
    <div class="card-content-left">
      <h2><%= rental.bike.name.titleize %></h2>
      <p>small content</p>
    </div>

    <div class="card-content-right">
      <h2>Toto</h2>
      <p>small content</p>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar fixed-bottom navbar-expand-sm navbar-light navbar-lewagon">

  <div class="container border-top border-secondary">
    <%= link_to root_path, class: "nav-link" do %>
      <i class="fas fa-2x fa-search-location"></i>
    <% end %>

    <%= link_to bikes_path, class: "nav-link" do %>
      <i class="fas fa-2x fa-bicycle"></i>
    <% end %>

    <%= link_to rentals_path, class: "nav-link" do %>
      <i class="fas fa-2x fa-shopping-cart"></i>
    <% end %>

    <% if current_user %>
      <%= link_to destroy_user_session_path, method: :delete, class: "nav-link" do %>
        <i class="fas fa-2x fa-sign-out-alt"></i>
      <% end %>
    <% else %>
      <%= link_to new_user_session_path, class: "nav-link" do %>
        <i class="fas fa-2x fa-user"></i>
      <% end %>
    <% end %>

  </div>

</div>

app/views/shared/_top_navbar.html.erb
<nav class="navbar navbar-light bg-primary">
    <span class="navbar-brand mb-0 h1 text-info mx-auto border-bottom border-info"><%= title %></span>
</nav>